CREATE DATABASE EOH002D
USE EOH002D;

CREATE TABLE PRODUCTO(
	ProductId NVARCHAR(255) NOT NULL PRIMARY KEY, 
	Name NVARCHAR(255) NOT NULL,
	ProductNumber NVARCHAR(255) NOT NULL
)

CREATE TABLE FECHA(
	IdTiempo NVARCHAR(255) NOT NULL PRIMARY KEY,
	ModifiedDate DATETIME NOT NULL
)

CREATE TABLE TOTAL(
	IdVendido INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdProducto NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ProductId),
	IdFecha NVARCHAR(255) FOREIGN KEY REFERENCES FECHA(IdTiempo),
	Fecha DATETIME,
	TOTAL INT NOT NULL
)

SELECT * FROM PRODUCTO
SELECT * FROM FECHA
SELECT * FROM TOTAL